In [1]:
#Garcia Sanchez Brandon Fabian - 1951 - Sistemas
import numpy as np
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.09214098, 0.05604204, 0.67246585],
       [0.39371546, 0.57240804, 0.42250344],
       [0.94881653, 0.95598494, 0.44829449],
       [0.06662801, 0.07648353, 0.52468266]])

In [4]:
arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[7, 9, 5],
       [0, 2, 4]])

In [5]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [6]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [7]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.delete(arr_ent,1,axis=1)

array([[7, 5],
       [0, 4]])