In [6]:
#Garcia Sanchez Brandon Fabian - 1951 - Sistemas
import numpy as np
a = np.array([2,4,9], float)

In [9]:
a

array([2., 4., 9.])

In [10]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [11]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [12]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [13]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [14]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [15]:
np.mean(a)

5.0

In [16]:
np.std(a)

2.943920288775949

In [17]:
np.var(a)

8.666666666666666