In [1]:
#Garcia Sanchez Brandon Fabian - 1951 - Sistemas
import numpy as np
arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[93, 49, 12, 66],
       [84, 64, 31, 10],
       [18, 55,  3,  3]])

In [2]:
arr_ent.astype(float)

array([[93., 49., 12., 66.],
       [84., 64., 31., 10.],
       [18., 55.,  3.,  3.]])

In [3]:
arr_ent

array([[93, 49, 12, 66],
       [84, 64, 31, 10],
       [18, 55,  3,  3]])

In [4]:
arr_ent.sort()
arr_ent

array([[12, 49, 66, 93],
       [10, 31, 64, 84],
       [ 3,  3, 18, 55]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 3,  3, 18, 55],
       [10, 31, 64, 84],
       [12, 49, 66, 93]])

In [6]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 3,  3, 18],
       [55, 10, 31],
       [64, 84, 12],
       [49, 66, 93]])

In [8]:
plano_arr = arr_ent.flatten()
print(arr_ent)
print(plano_arr)

[[ 3  3 18]
 [55 10 31]
 [64 84 12]
 [49 66 93]]
[ 3  3 18 55 10 31 64 84 12 49 66 93]


In [9]:
lista_arr = plano_arr.tolist()
lista_arr

[3, 3, 18, 55, 10, 31, 64, 84, 12, 49, 66, 93]

In [10]:
arrays = np.split(arr_ent,4)
arrays

[array([[ 3,  3, 18]]),
 array([[55, 10, 31]]),
 array([[64, 84, 12]]),
 array([[49, 66, 93]])]

In [11]:
np.concatenate((arrays[1], arrays[0]),axis=0)

array([[55, 10, 31],
       [ 3,  3, 18]])

In [12]:
t_arr = arr_ent.T
t_arr

array([[ 3, 55, 64, 49],
       [ 3, 10, 84, 66],
       [18, 31, 12, 93]])